In [1]:
import pandas as pd

In [5]:
path = '../data/raw/metadata.csv'
df = pd.read_csv(path)

In [6]:
df.head()

,building_id,site_id,building_id_kaggle,site_id_kaggle,primaryspaceusage,sub_primaryspaceusage,sqm,sqft,lat,lng,...,yearbuilt,date_opened,numberoffloors,occupants,energystarscore,eui,site_eui,source_eui,leed_level,rating
0,Panther_lodging_Dean,Panther,NaN,0.0,Lodging/residential,Residence Hall,508.8,5477.0,28.517689,-81.379039,...,1989.0,NaN,NaN,NaN,NaN,271,NaN,NaN,NaN,NaN
1,Panther_lodging_Shelia,Panther,NaN,0.0,Lodging/residential,Residence Hall,929.0,10000.0,28.517689,-81.379039,...,1992.0,NaN,NaN,NaN,NaN,62,NaN,NaN,NaN,NaN
2,Panther_lodging_Ricky,Panther,NaN,0.0,Lodging/residential,Residence Hall,483.1,5200.0,28.517689,-81.379039,...,2016.0,NaN,NaN,NaN,NaN,534,NaN,NaN,NaN,NaN
3,Panther_education_Rosalie,Panther,0.0,0.0,Education,Research,690.5,7432.0,28.517689,-81.379039,...,2008.0,NaN,NaN,NaN,NaN,276,NaN,NaN,NaN,NaN
4,Panther_education_Misty,Panther,1.0,0.0,Education,Research,252.7,2720.0,28.517689,-81.379039,...,2004.0,NaN,NaN,NaN,NaN,375,NaN,NaN,NaN,NaN

In [7]:
rows, cols = df.shape

In [8]:
print(rows, cols)

1636 32

In [17]:
df["electricity"].value_counts(dropna=False)

electricity
Yes    1578
NaN      58
Name: count, dtype: int64

In [18]:
elec = df[df["electricity"] == "Yes"]

In [19]:
len(elec)

1578

In [21]:
elec["site_id"].value_counts(dropna=False)

site_id
Rat         305
Hog         152
Lamb        146
Fox         137
Bull        123
Cockatoo    117
Eagle       106
Panther     105
Bear         92
Gator        74
Robin        52
Peacock      45
Wolf         36
Bobcat       35
Swan         19
Moose        13
Shrew         9
Mouse         7
Crow          5
Name: count, dtype: int64

In [22]:
df[["site_id", "timezone"]]

      site_id       timezone
0     Panther     US/Eastern
1     Panther     US/Eastern
2     Panther     US/Eastern
3     Panther     US/Eastern
4     Panther     US/Eastern
...       ...            ...
1631    Mouse  Europe/London
1632    Mouse  Europe/London
1633    Mouse  Europe/London
1634    Mouse  Europe/London
1635    Mouse  Europe/London

[1636 rows x 2 columns]

In [23]:
df[["site_id","timezone"]].drop_duplicates()

       site_id       timezone
0      Panther     US/Eastern
136      Robin  Europe/London
188        Fox    US/Mountain
325        Rat     US/Eastern
630       Bear     US/Pacific
722       Lamb  Europe/London
869    Peacock     US/Eastern
916      Moose     US/Eastern
931      Gator     US/Eastern
1005      Bull     US/Central
1129    Bobcat    US/Mountain
1165      Crow     US/Eastern
1170     Shrew  Europe/London
1179      Swan     US/Pacific
1200      Wolf  Europe/Dublin
1236       Hog     US/Central
1399     Eagle     US/Eastern
1505  Cockatoo     US/Eastern
1629     Mouse  Europe/London

In [24]:
df[["site_id","timezone"]].drop_duplicates().value_counts()

site_id   timezone
Panther   US/Eastern       1
Robin     Europe/London    1
Fox       US/Mountain      1
Rat       US/Eastern       1
Bear      US/Pacific       1
Lamb      Europe/London    1
Peacock   US/Eastern       1
Moose     US/Eastern       1
Gator     US/Eastern       1
Bull      US/Central       1
Bobcat    US/Mountain      1
Crow      US/Eastern       1
Shrew     Europe/London    1
Swan      US/Pacific       1
Wolf      Europe/Dublin    1
Hog       US/Central       1
Eagle     US/Eastern       1
Cockatoo  US/Eastern       1
Mouse     Europe/London    1
Name: count, dtype: int64

In [ ]:
sum(df[["site_id","timezone"]].drop_duplicates().value_counts())